version: "3"

services:
  php:
    build: ./docker/phpfpm
    volumes:
      - ./:/var/www
  mysql:
    build: ./docker/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--disable-partition-engine-check"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
  redis:
    image: redis
  phpmyadmin:
      build: ./docker/phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - MYSQL_USER=phpmyadmin
        - MYSQL_PASSWORD=123456
        - MYSQL_ROOT_PASSWORD=123456
      ports:
        - "9999:80"
      depends_on:
        - "mysql"
  web:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes: 
      - ./:/var/www
      - ./docker/nginx/sites:/etc/nginx/conf.d
    links:
      - php
      - mysql
      - redis